name: fastguide
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: "^1.3.0"
  firebase_auth: "^1.4.1"
  cloud_firestore: "^2.2.2"
  provider: ^5.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  timeago: ^3.1.0
  url_launcher: ^6.0.9
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.1
  cached_network_image: ^3.0.0
  chewie: ^1.2.2
  video_player: ^2.1.6
  webview_flutter: ^2.0.10
  share: ^2.0.4
  device_info: ^2.0.2
  flutter_windowmanager: ^0.1.0
  # andea project package 
  path_provider: ^2.0.2
  google_sign_in: ^5.0.4
  random_string: ^2.1.0
  animated_text_kit: ^4.2.1
  flutter_native_splash: ^1.2.0
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  syncfusion_flutter_pdfviewer: ^19.2.51-beta
  font_awesome_flutter: ^9.1.0
  new_version: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - data/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Fredoka One
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Medium.ttf

    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-Regular.ttf
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mukta-Light.ttf
        - asset: assets/fonts/Mukta-Medium.ttf


    - family: Vesper Libre
      fonts:
        - asset: assets/fonts/VesperLibre-Bold.ttf
        - asset: assets/fonts/VesperLibre-Regular.ttf                
        - asset: assets/fonts/VesperLibre-Medium.ttf
